version: '3.7'

services:
  app-db:
    image: mysql:8
    restart: always
    ports:
     - "3306:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: offdays
      MYSQL_USER: user
      MYSQL_PASSWORD: secret

  app:
    image: holiday-calculator:latest
    build:
      context: ./holidayCalculator
    restart: always
    ports:
     - "8080:8080"
    environment: 
      DATABASE_URL: app-db
    
    
  phpmyadmin:
    depends_on:
     - app-db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
     - '8888:80'
    links:
     - app-db
    environment:
      PMA_HOST: app-db

